### ISSUE TITLE
ISIN Request Foreign_Exchange.Forward.Forward.InstRefDataReporting

### ISSUE THREAD

**Issue by BhuvaneshBabu** [ANNA-DSB/Functionality#16]
We observed a behaviour in the ISIN request in template, Foreign_Exchange.Forward.Forward.InstRefDataReporting.V1 which we feel is an issue. 

For the following ISIN requests, we sent the Notional Currency and Other notional currency as follows,

Notional Currency, Other Notional Currency
ZAR, EUR
USD, INR
EUR, AUD

But in the response, the notional currency and other currency are re-aligned per alphabetical order,

Notional Currency, Other Notional Currency
EUR, ZAR
INR, USD
AUD, EUR

Can you please advise on this behaviour.

**Comment by AnnaDSBTechnicalSupport** [comment]
Hi, Bhuvanesh.

This is an expected behavior of the system which covered in our normalization rules.
You can find the FX normalisation rules and documentation under https://github.com/ANNA-DSB/Product-Definitions/blob/master/UAT/docs/DSB%20UAT%20Product%20Definitions.pdf in section 7.3 FX normalization.

Going forward, please send your concerns/queries to DSB technical support at technical.support@ANNA-DSB.com

Regards,
DSB Technical Support Team
